parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        default_connection: hooli
        connections:
            hooli:
                driver: 'pdo_pgsql'
                server_version: '9.4'
                url: '%env(resolve:DB_HOOLI_URL)%'
                charset: UTF8
            customer:
                driver: 'pdo_pgsql'
                server_version: '9.4'
                url: '%env(resolve:DB_CUSTOMER_URL)%'
                charset: UTF8

    orm:
        default_entity_manager: hooli
        auto_generate_proxy_classes: '%kernel.debug%'
        entity_managers:
            hooli:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                connection: hooli
                mappings:
                    Main:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Hooli'
                        prefix: 'App\Entity\Hooli'
                        alias: Hooli
            customer:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                connection: customer
                mappings:
                    Customer:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Customer'
                        prefix: 'App\Entity\Customer'
                        alias: Customer